<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>loginButton</name>
   <tag></tag>
   <elementGuidId>58721739-515a-41ff-a68f-b9aeb7c66dd0</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>a.gb_va.gb_nd.gb_ed.gb_9d</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='gb']/div/div[2]/a</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>a</value>
      <webElementGuid>3c255af0-caba-42e0-b5d6-0fcabe0214b0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>gb_va gb_nd gb_ed gb_9d</value>
      <webElementGuid>80a6d34d-d8a0-4a93-8b21-58d0184db16b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>a35b8644-3892-4afe-82a4-48f88dd0145d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>href</name>
      <type>Main</type>
      <value>https://accounts.google.com/ServiceLogin?hl=id&amp;passive=true&amp;continue=https://www.google.co.id/%3Fhl%3Did&amp;ec=GAZAmgQ</value>
      <webElementGuid>b8089178-6869-4b8d-ac1c-5c4d9d719732</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>target</name>
      <type>Main</type>
      <value>_top</value>
      <webElementGuid>59a48565-05c8-4eb6-855b-d4580d9b5938</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Login</value>
      <webElementGuid>19c87ee2-f927-4f39-991c-69453db2fbee</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;gb&quot;)/div[@class=&quot;gb_ud gb_7a gb_id&quot;]/div[@class=&quot;gb_Ld&quot;]/a[@class=&quot;gb_va gb_nd gb_ed gb_9d&quot;]</value>
      <webElementGuid>6c6efbc1-8a0c-4e41-8868-8eedf1c809e0</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='gb']/div/div[2]/a</value>
      <webElementGuid>d9b23a6d-2dd4-45b2-b1a5-245d0c337f87</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gambar'])[1]/following::a[2]</value>
      <webElementGuid>57ff4b0d-c4e9-4146-bd50-fcf6af54c2c8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Gmail'])[1]/following::a[3]</value>
      <webElementGuid>8e50154f-e5b7-4d1a-bc07-33379ec5d43d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pilih elemen yang akan diberi masukan'])[1]/preceding::a[1]</value>
      <webElementGuid>370b510c-5d8b-40e8-be7e-c4900df8711e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:href</name>
      <type>Main</type>
      <value>//a[contains(@href, 'https://accounts.google.com/ServiceLogin?hl=id&amp;passive=true&amp;continue=https://www.google.co.id/%3Fhl%3Did&amp;ec=GAZAmgQ')]</value>
      <webElementGuid>17a22ab2-daf6-4807-a6a3-a9e076b291aa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//body/div/div/div/div/div/div/div[2]/a</value>
      <webElementGuid>e4cd7167-9f42-426d-8a18-9f2b0cbbbc70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//a[@href = 'https://accounts.google.com/ServiceLogin?hl=id&amp;passive=true&amp;continue=https://www.google.co.id/%3Fhl%3Did&amp;ec=GAZAmgQ' and (text() = 'Login' or . = 'Login')]</value>
      <webElementGuid>577b16f9-5481-4bc3-8295-ef03726f2ab7</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
